# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build producer
        run: docker build -t ghcr.io/modulus/servicebus-typescript-demo-producer:latest -f Dockerfile.sender .
      - name: Docker push
        run: docker push ghcr.io/modulus/servicebus-typescript-demo-producer:latest
      - name: Docker build receiver
        run: docker build -t ghcr.io/modulus/servicebus-typescript-demo-receiver:latest -f Dockerfile.receiver .
      - name: Push reveiver container
        run: docker push ghcr.io/modulus/servicebus-typescript-demo-receiver:latest 

        